<?php

namespace stesi\maplocation;

use yii\web\AssetBundle;
use yii\web\View;

/**
 * SelectMapLocationWidget assets class
 *
 * @author Max Kalyabin <maksim@kalyabin.ru>
 * @package yii2-select-google-map-location
 * @copyright (c) 2015, Max Kalyabin, http://github.com/kalyabin
 */
class GoogleMapsAssets extends AssetBundle
{
    public $sourcePath = '@vendor/stesi/yii2-select-google-map-location';
    public $css = ['css/yii2-select-google-map-location.css'];
    public $js = [


    ];
    public $depends = [
        'yii\web\YiiAsset',
    ];
    public static $googleMapApiKey;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        /* @var $view \yii\web\View */
        if (empty(self::$googleMapApiKey)) {
            self::$googleMapApiKey = \Yii::$app->params['googleMapApiKey'];
        }
        //  $view->registerJs("function loadedMap(){ $('.maps_widget').trigger('map_api_loaded');}", View::POS_LOAD);
      /*  $view->registerJsFile('https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&sensor=true&key=' . self::$googleMapApiKey );*/
        $this->js[] = 'https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&sensor=true&key=' . self::$googleMapApiKey;
    }

    /**
     * @inheritdoc
     */
    public static function register($view)
    {

        return parent::register($view);
    }
}
